### ISSUE TITLE
Segmentation fault (core dumped): general protection fault

### ISSUE THREAD

**Issue by dstruck** [taviso/loadlibrary#75]
**mpclient** fails with the newest engine download (2020-01-31) with a `Segmentation fault (core dumped)` message.

In the logs we see the following message:

`traps: mpclient[16028] general protection fault ip:5a39a82b sp:ffd38b78 error:14a`

**Comment by jlorgal** [comment]
Yes, I also confirm that it stopped working.
Just if it could help, this is some information I've recollected.

```
exiftool mpengine.dll
ExifTool Version Number         : 11.16
File Name                       : mpengine.dll
Directory                       : .
File Size                       : 11 MB
File Modification Date/Time     : 2020:02:06 10:35:58+00:00
File Access Date/Time           : 2020:02:06 10:35:58+00:00
File Inode Change Date/Time     : 2020:02:06 10:35:58+00:00
File Permissions                : rw-r--r--
File Type                       : Win32 DLL
File Type Extension             : dll
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2020:01:24 20:22:21+00:00
Image File Characteristics      : Executable, 32-bit, DLL
PE Type                         : PE32
Linker Version                  : 14.20
Code Size                       : 10669568
Initialized Data Size           : 1075712
Uninitialized Data Size         : 0
Entry Point                     : 0x2a3570
OS Version                      : 10.0
Image Version                   : 10.0
Subsystem Version               : 6.0
Subsystem                       : Windows command line
File Version Number             : 1.1.16700.3
Product Version Number          : 1.1.16700.3
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Windows NT 32-bit
Object File Type                : Dynamic link library
File Subtype                    : 0
Language Code                   : English (U.S.)
Character Set                   : Unicode
Company Name                    : Microsoft Corporation
File Description                : Microsoft Malware Protection Engine
Internal Name                   : mpengine
Legal Copyright                 : © Microsoft Corporation. All rights reserved.
Original File Name              : mpengine.dll
Product Name                    : Microsoft Malware Protection
File Version                    : 1.1.16700.3 (750aed32656f86ce9767a8d5f0bcc470de568ef5)
Product Version                 : 1.1.16700.3
```

```
root@ae2870511c8b:/usr/loadlibrary# gdb ./mpclient
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./mpclient...done.
(gdb) run
Starting program: /usr/loadlibrary/mpclient
warning: Error disabling address space randomization: Operation not permitted

Program received signal SIGSEGV, Segmentation fault.
0x5a39a82b in ?? ()
(gdb) bt
#0  0x5a39a82b in ?? ()
#1  0x5a63e152 in ?? ()
#2  0x5a63e00b in ?? ()
#3  0x5a63e311 in ?? ()
#4  0x5a4c6cac in ?? ()
#5  0x5a4a4745 in ?? ()
#6  0x5a4a33e4 in ?? ()
#7  0x5a4a108f in ?? ()
#8  0x5a3d3abd in ?? ()
#9  0x5a3d45ed in ?? ()
#10 0x5a3d49fb in ?? ()
#11 0x5a3d4029 in ?? ()
#12 0x5a3d506e in ?? ()
#13 0x5656b7a8 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at mpclient.c:224
(gdb) x/i $pc
=> 0x5a39a82b:  int    $0x29
(gdb) i r
eax            0x1                 1
ecx            0x7                 7
edx            0x17                23
ebx            0x572fb470          1462744176
esp            0xffab1758          0xffab1758
ebp            0xffab1784          0xffab1784
esi            0x0                 0
edi            0xffab183c          -5564356
eip            0x5a39a82b          0x5a39a82b
eflags         0x10202             [ IF RF ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x73                115
gs             0x63                99
(gdb) frame 1
#1  0x5a63e152 in ?? ()
(gdb) p image
No symbol "image" in current context.
```

**Comment by LordNoteworthy** [comment]
I can confirm the issue again :(

**Comment by taviso** [comment]
Thanks, I can reproduce the crash and have just been waiting for symbols to figure out what's going on. Microsoft *still* hasn't released symbols for this build yet, it's been nearly a month 😞 

It's a real pain to debug without symbols, but if they don't release the symbols soon, I'll try to debug it without symbols.

**Comment by LordNoteworthy** [comment]
Thanks a lot @taviso

**Comment by Ldundun** [comment]
Mark, I also have this question on Centos 7

**Comment by taviso** [comment]
The PDB just appeared on the symbol server, I'll take a look on Monday. Sorry for the delay!

**Comment by taviso** [comment]
I think I see the problem. I've got a workaround, please file a bug if it doesn't work properly.

**Comment by dstruck** [comment]
Works.
